image: rust:latest

stages:
  - build
  - test_unit

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y clang
    - cd ..
    - rm -rf vade
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade.git --branch develop
    - cd vade-universal-resolver
    - cargo build --release --verbose
  artifacts:
    paths:
      - ./target
    expire_in: 1 hour

test_unit:
  stage: test_unit
  script:
    - cargo test --release --verbose
