[package]
name = "vade-universal-resolver"
version = "0.1.0"
authors = ["Devraj Singh <dsrawat@blockchains.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
